apiVersion: apps/v1
kind: Deployment
metadata:
  name: amqp-metrics
spec:
  replicas: 1
  selector:
   matchLabels:
      app: amqp-metrics
  template:
    metadata:
      labels:
        app: prom-rabbitmq-metrics
    spec:
      containers:
      - name: prometheus
        image: kbudde/rabbitmq-exporter:v0.29.0
        env:
        - name: RABBIT_URL
          value: http://10.52.7.167:15672
        - name: RABBIT_USER
          value: user
        - name: RABBIT_PASSWORD
          value: Rabbit_test
        - name: PUBLISH_PORT
          value: "9419"
        # amqp 3.6.9++
        - name: RABBIT_CAPABILITIES
          value: "bert,no_sort"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.2.3
        command:
        - /monitor
        - --source=:http://localhost:9419
        - --stackdriver-prefix=custom.googleapis.com
        - --pod-id=$(POD_ID)
        - --namespace-id=$(POD_NAMESPACE)
        env:
        - name: POD_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
