apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: workers-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metricName: 'custom.googleapis.com|rabbitmq_queue_messages_ready'
      metricSelector:
        matchLabels:
          metric.labels.queue: testqueue
      targetValue: 10
